# Generated by Django 4.2.28 on 2026-03-02 00:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(max_length=10, verbose_name='Hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('canal_contacto', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefono', 'Telefono'), ('email', 'Email'), ('presencial', 'Presencial')], default='whatsapp', max_length=20, verbose_name='Canal de Contacto')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s-]{7,15}$', 'Numero de telefono invalido')], verbose_name='Telefono')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Numero de Documento')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('direccion', models.TextField(blank=True, verbose_name='Direccion')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envio')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('numero_guia', models.CharField(max_length=100, unique=True, verbose_name='Numero de Guia')),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('despachado', 'Despachado'), ('en_transito', 'En Transito'), ('entregado', 'Entregado')], default='preparando', max_length=20, verbose_name='Estado')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Envio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Ano')),
                ('cilindrada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cilindrada (cc)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio (COP)')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('categoria', models.CharField(choices=[('sport', 'Sport'), ('touring', 'Touring'), ('naked', 'Naked'), ('adventure', 'Adventure'), ('scooter', 'Scooter')], default='sport', max_length=20, verbose_name='Categoria')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['categoria', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numero de Pedido')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En Preparacion'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='motos.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('pse', 'PSE'), ('transferencia', 'Transferencia'), ('credito', 'Credito')], max_length=20, verbose_name='Metodo de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('referencia', models.CharField(max_length=100, unique=True, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='motos.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['categoria'], name='motos_moto_categor_3cfd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='moto',
            index=models.Index(fields=['stock'], name='motos_moto_stock_2e50d1_idx'),
        ),
        migrations.AddField(
            model_name='envio',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envio', to='motos.pedido'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='motos.cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='motos.moto'),
        ),
    ]
