# Generated by Django 6.0.3 on 2026-04-11 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_remove_pago_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mercadopago', 'Mercado Pago')], default='mercadopago', max_length=30)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='creado', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('external_reference', models.CharField(max_length=120, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('detalle_estado', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='motos.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado'], name='motos_pago_estado_idx'), models.Index(fields=['gateway'], name='motos_pago_gateway_idx'), models.Index(fields=['external_reference'], name='motos_pago_extref_idx')],
            },
        ),
    ]
